config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :favorites, only: %i[index create destroy]
  delete '/favorites', to: 'favorites#delete_by_movie_id'
  resources :likes, only: %i[index create update destroy]

  resources :movies, only: %i[index] do
    collection do
      get '/discover', to: 'movies#discover'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  validates :movie_id, presence: true, uniqueness: { scope: :user }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  validates :movie_id, presence: true, uniqueness: { scope: :user }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: { scope: :user }
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :users
  validates :imdb_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :movies, through: :favorites
  has_one_attached :photo
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :find_list

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite = Favorite.new
    @favorites = current_user.favorites
    @movies = my_favorite_movies
    respond_to do |format|
      format.html
      format.json { render 'create' }
    end
  end

  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.user = current_user
    @favorites = current_user.favorites
    respond_to do |format|
      if @favorite.save
        format.json
      else
        redirect_to root_path, alert: 'Something went wrong when adding to favorites'
      end
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @movie = @favorite.movie_id
    @favorites = current_user.favorites
    @favorite.destroy
    respond_to do |format|
      if @favorite.destroyed?
        format.json
      else
        redirect_to root_path, alert: 'Something went wrong when removing from favorites'
      end
    end
  end

  def delete_by_movie_id
    @favorite = current_user.favorites.find_by(movie_id: params[:movie_id])
    @favorite.destroy
    redirect_to favorites_path, notice: 'Removed from favorites'
  end

  private

  def my_favorite_movies
    favorites = current_user.favorites
    favorite_movies = []

    favorites.each do |favorite|
      favorite_movies << find_movie(favorite.movie_id)
    end
    favorite_movies
  end

  def find_movie(movie_id)
    url = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{ENV["TMDB_KEY"]}"
    movie_serialized = URI.parse(url).read
    return JSON.parse(movie_serialized) if JSON.parse(movie_serialized)

    {}
  end

  def favorite_params
    params.require(:favorite).permit(:movie_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likes, only: %i[index create update destroy]
  before_action :set_like, only: %i[update destroy]

  def index
    @like = Like.new
    respond_to do |format|
      format.html
      format.json { render 'create' }
    end
  end

  def create
    @like = Like.new(like_params)
    @like.user = current_user
    respond_to do |format|
      if @like.save
        format.json
      else
        redirect_to root_path, alert: 'Something went wrong when adding to likes'
      end
    end
  end

  def update
    respond_to do |format|
      if @like.update(like_params)
        format.json { render 'create' }
      else
        redirect_to root_path, alert: 'Something went wrong when updating likes'
      end
    end
  end

  def destroy
    @movie = @like.movie_id
    @like.destroy
    respond_to do |format|
      if @like.destroyed?
        format.json
      else
        redirect_to root_path, alert: 'Something went wrong when removing from likes'
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:movie_id, :liked)
  end

  def set_likes
    @likes = current_user.likes
  end

  def set_like
    @like = Like.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def featured
    @lists = List.order(:name)
  end

  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = if params[:query].present?
                search_movies(params[:query])
              else
                {}
              end
    @favorite = Favorite.new
    @like = Like.new
    respond_to do |format|
      format.html
      format.json { render json: { movies: @movies, favorites: @favorites } }
    end
  end

  def discover
    @movies = fetch_movies(categories)
    @favorite = Favorite.new
    @like = Like.new
    @favorites = current_user.favorites
    @likes = current_user.likes
    respond_to do |format|
      format.html
      format.json { render json: { movies: @movies, favorites: @favorites, likes: @likes, favorite: @favorite } }
    end
  end

  private

  def categories
    %w[latest now_playing popular top_rated upcoming]
  end

  def fetch_movies(categories, page = 1)
    movies_hash = {}

    categories.each do |category|
      url = "https://api.themoviedb.org/3/movie/#{category}?api_key=#{ENV["TMDB_KEY"]}&page=#{page}"
      movies_serialized = URI.parse(url).read
      if JSON.parse(movies_serialized)['results']
        movies_hash[category.to_sym] = JSON.parse(movies_serialized)['results']
      end
    end
    movies_hash
  end

  def search_movies(query, page = 1)
    url = "https://api.themoviedb.org/3/search/multi?api_key=#{ENV["TMDB_KEY"]}&query=#{query}&page=#{page}"
    movies_serialized = URI.parse(url).read
    return JSON.parse(movies_serialized)['results'] if JSON.parse(movies_serialized)['results']
  end

  def find_movie(movie_id)
    url = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{ENV["TMDB_KEY"]}"
    movie_serialized = URI.parse(url).read
    return JSON.parse(movie_serialized) if JSON.parse(movie_serialized)

    {}
  end

  def find_video(movie_id)
    url = "https://api.themoviedb.org/3/movie/#{movie_id}/videos?api_key=#{ENV["TMDB_KEY"]}"
    movie_serialized = URI.parse(url).read
    return JSON.parse(movie_serialized) if JSON.parse(movie_serialized)

    {}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-100 banner-lg">
  <div class="background-black-soft d-flex flex-column align-items-center justify-content-center">
    <h1 class="font-brand">WatchList</h1>
    <h3 class="font-tag">Browse, create and share lists of your favorite movies</h3>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class='grid-three'>
    <div>
      <%= image_tag asset_path('tmdb_logo.svg') %>
      <p class="tmdb-disclaimer">This product uses the TMDB API but is not endorsed or certified by TMDB.</p>
    </div>

    <div class="footer-copyright">
      Made with <i class="fas fa-heart"></i> by Aris
    </div>

    <div class="footer-links">
      <a href="https://aristorap.herokuapp.com" target="_blank">Portfolio</i></a>

      <a href="https://github.com/AristoRap"
         target="_blank"
         title='My GitHub'>
         <i class="fab fa-github"></i>
      </a>

      <a href="https://www.linkedin.com/in/aristoteles-rapai-16a261137/"
         target="_blank"
         title='My GitHub'>
         <i class="fab fa-linkedin"></i>
      </a>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg sticky-top navbar-lewagon px-5 py-3">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to 'WatchList', discover_movies_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to 'WatchList', root_path , class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mr-auto align-items-center">
        <% if user_signed_in? %>
          <li class="mr-2">
            <div class="search-box" data-controller='search-bar'>
              <%= form_tag movies_path, method: :get, class: 'input-group search-form align-items-center justify-content-between' do %>
                  <i class="text-white fa fa-search search-box-icon" data-search-bar-target='searchBtn' name='commit' value='search'></i>
                  <%= text_field_tag :query,
                      params[:query],
                      class: "search-box-input round-one",
                      placeholder: "Search for a title",
                      required: true,
                      data: { search_bar_target: 'searchBar',
                              action: 'keyup->search-bar#preview' }
                    %>
              <% end %>
              <ul id="search-results">
              </ul>
            </div>
          </li>

          <li class="nav-item active">
            <%= link_to "Discover", discover_movies_path %>
          </li>

          <li class="nav-item">
            <%= link_to 'Favorites', favorites_path %>
          </li>

          <li class="dropdown">
            <a class="avatar ml-2" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, height: 40, width: 40, class:'avatar'%>
              <% else %>
                <%= image_tag asset_path('avatar_default.png'), class: 'avatar' %>
              <% end %>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>